// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2jwa7XHvRVGB00olD5ePzZ7t0J5ROh0Y',
    appId: '1:434262526780:web:246ae40324667d57ff6c39',
    messagingSenderId: '434262526780',
    projectId: 'somcabledatabase',
    authDomain: 'somcabledatabase.firebaseapp.com',
    storageBucket: 'somcabledatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClYjs_wPQ9KHal4nBDrAYfd1l6iVT5m5w',
    appId: '1:434262526780:android:5444075b9ac4d105ff6c39',
    messagingSenderId: '434262526780',
    projectId: 'somcabledatabase',
    storageBucket: 'somcabledatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBBCA53R5z5LEZo2p0NTFIZ_OboyEbss',
    appId: '1:434262526780:ios:4c4de12367b6cf3fff6c39',
    messagingSenderId: '434262526780',
    projectId: 'somcabledatabase',
    storageBucket: 'somcabledatabase.appspot.com',
    iosClientId: '434262526780-c6s6b9d6ppl46bk5mck6n10umlbv20ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.somcableWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBBCA53R5z5LEZo2p0NTFIZ_OboyEbss',
    appId: '1:434262526780:ios:4c4de12367b6cf3fff6c39',
    messagingSenderId: '434262526780',
    projectId: 'somcabledatabase',
    storageBucket: 'somcabledatabase.appspot.com',
    iosClientId: '434262526780-c6s6b9d6ppl46bk5mck6n10umlbv20ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.somcableWebApp',
  );
}
